### ISSUE TITLE
error  when use " python3 -m unittest " command

### ISSUE THREAD

**Issue by aeworks** [nils-wisiol/pypuf#121]
Hi, I am try to install pypuf but I have the next error

`======================================================================
ERROR: test.test_example (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_example
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/aerobles/Descargas/pypuf/pypuf-master/test/test_example.py", line 6, in <module>
    import example
  File "/home/aerobles/Descargas/pypuf/pypuf-master/example.py", line 5, in <module>
    from pypuf.learner.regression.logistic_regression import LogisticRegression
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/learner/regression/logistic_regression.py", line 11, in <module>
    from pypuf.simulation.arbiter_based.ltfarray import LTFArray
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/simulation/arbiter_based/ltfarray.py", line 10, in <module>
    import pypuf_helper as ph
SystemError: initialization of pypuf_helper raised unreported exception

======================================================================
ERROR: test.test_experiment (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_experiment
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/aerobles/Descargas/pypuf/pypuf-master/test/test_experiment.py", line 4, in <module>
    from pypuf.simulation.arbiter_based.ltfarray import LTFArray, NoisyLTFArray
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/simulation/arbiter_based/ltfarray.py", line 10, in <module>
    import pypuf_helper as ph
SystemError: initialization of pypuf_helper raised unreported exception

======================================================================
ERROR: test.test_experimenter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_experimenter
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/aerobles/Descargas/pypuf/pypuf-master/test/test_experimenter.py", line 5, in <module>
    from pypuf.simulation.arbiter_based.ltfarray import LTFArray, NoisyLTFArray
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/simulation/arbiter_based/ltfarray.py", line 10, in <module>
    import pypuf_helper as ph
SystemError: initialization of pypuf_helper raised unreported exception

======================================================================
ERROR: test.test_logistic_regression (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_logistic_regression
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/aerobles/Descargas/pypuf/pypuf-master/test/test_logistic_regression.py", line 4, in <module>
    from pypuf.simulation.arbiter_based.ltfarray import LTFArray
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/simulation/arbiter_based/ltfarray.py", line 10, in <module>
    import pypuf_helper as ph
SystemError: initialization of pypuf_helper raised unreported exception

======================================================================
ERROR: test.test_low_degree (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_low_degree
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/aerobles/Descargas/pypuf/pypuf-master/test/test_low_degree.py", line 6, in <module>
    from pypuf.simulation.arbiter_based.ltfarray import LTFArray
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/simulation/arbiter_based/ltfarray.py", line 10, in <module>
    import pypuf_helper as ph
SystemError: initialization of pypuf_helper raised unreported exception

======================================================================
ERROR: test.test_mv_num_of_votes (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_mv_num_of_votes
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/aerobles/Descargas/pypuf/pypuf-master/test/test_mv_num_of_votes.py", line 7, in <module>
    import mv_num_of_votes
  File "/home/aerobles/Descargas/pypuf/pypuf-master/mv_num_of_votes.py", line 36, in <module>
    from pypuf.experiments.experiment.majority_vote import ExperimentMajorityVoteFindVotes
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/experiments/experiment/majority_vote.py", line 10, in <module>
    from pypuf.simulation.arbiter_based.ltfarray import SimulationMajorityLTFArray, LTFArray, NoisyLTFArray
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/simulation/arbiter_based/ltfarray.py", line 10, in <module>
    import pypuf_helper as ph
SystemError: initialization of pypuf_helper raised unreported exception

======================================================================
ERROR: test.test_property (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_property
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/aerobles/Descargas/pypuf/pypuf-master/test/test_property.py", line 6, in <module>
    from pypuf.simulation.arbiter_based.ltfarray import LTFArray, NoisyLTFArray
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/simulation/arbiter_based/ltfarray.py", line 10, in <module>
    import pypuf_helper as ph
SystemError: initialization of pypuf_helper raised unreported exception

======================================================================
ERROR: test.test_sim_learn (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_sim_learn
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/aerobles/Descargas/pypuf/pypuf-master/test/test_sim_learn.py", line 4, in <module>
    import sim_learn
  File "/home/aerobles/Descargas/pypuf/pypuf-master/sim_learn.py", line 7, in <module>
    from pypuf.simulation.arbiter_based.ltfarray import LTFArray
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/simulation/arbiter_based/ltfarray.py", line 10, in <module>
    import pypuf_helper as ph
SystemError: initialization of pypuf_helper raised unreported exception

======================================================================
ERROR: test.test_simulation (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_simulation
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/aerobles/Descargas/pypuf/pypuf-master/test/test_simulation.py", line 7, in <module>
    from pypuf.simulation.arbiter_based.ltfarray import LTFArray, NoisyLTFArray, SimulationMajorityLTFArray
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/simulation/arbiter_based/ltfarray.py", line 10, in <module>
    import pypuf_helper as ph
SystemError: initialization of pypuf_helper raised unreported exception

======================================================================
ERROR: test.test_tools (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_tools
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/aerobles/Descargas/pypuf/pypuf-master/test/test_tools.py", line 6, in <module>
    from pypuf.simulation.arbiter_based.ltfarray import LTFArray
  File "/home/aerobles/Descargas/pypuf/pypuf-master/pypuf/simulation/arbiter_based/ltfarray.py", line 10, in <module>
    import pypuf_helper as ph
SystemError: initialization of pypuf_helper raised unreported exception

----------------------------------------------------------------------
Ran 10 tests in 0.006s

FAILED (errors=10)
`

**Comment by MrM0nkey** [comment]
Sometimes pip "fail" to install some packages especially "pypuf_helper" and "polymath".
A workaround for me was to uninstall all packages
BEWARE! ONLY USE THIS COMMAND WITH A VIRTUAL ENVIRONMENT
`$pip freeze | xargs pip uninstall -y`
and reinstall them with
`$pip install --no-cache-dir -r requirements.txt `
Be sure you use a virtual environment when uninstalling all packages. If you do not use a virtual environment, you could try to un- and reinstall "pypuf_helper" and "polymath" manually but be sure to use the "--no-cache-dir" option on pip.

**Comment by aeworks** [comment]
Thanks, it works, but I have to delete all project and unzip again. Next in the moment to intall the  requeriments, I used `$pip install --no-cache-dir -r requirements.txt`. Thanks a lot for your help.

**Comment by nils-wisiol** [comment]
does anyone know how to reproduce this problem?

**Comment by aeworks** [comment]
If you try to install pyfpuf with commands found on the Readme, you have that problem when you execute `.python3 -m unittest`  or examples. The problem seem to be in the requeriment versions.
