### ISSUE TITLE
Liu: AttributeError: 'float' object has no attribute 'size'

### ISSUE THREAD

**Issue by nils-wisiol** [nils-wisiol/pypuf#35]
Traceback (most recent call last):
	  File "sim_learn.py", line 142, in <module>
		model = learner.learn()
	  File "/home/nils/git/pypuf/pypuf/learner/liu/polytope_algorithm.py", line 84, in learn
		(center,radius) = self.__chebyshev_center(challenges, responses)
	  File "/home/nils/git/pypuf/pypuf/learner/liu/polytope_algorithm.py", line 109, in __chebyshev_center
		return findCenter(challenges,responses)
	  File "/home/nils/git/pypuf/pypuf/learner/liu/chebyshev.py", line 43, in findCenter
		ret=zeros(result.x.size-1)
	AttributeError: 'float' object has no attribute 'size'

**Comment by nils-wisiol** [comment]
liu branch is stale
